server:
  port: 8100

spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:localhost://8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka