version: "3.9"

services:
  currency-exchange:
    image: prathi233/mmv2-currency-exchange:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    mem_reservation: 700m
    depends_on:
      - naming-server
      - rabbitmq
    networks:
      - currency-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  currecy-conversion:
    image: prathi233/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    mem_reservation: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  api-gateway:
    image: prathi233/mmv2-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    mem_reservation: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  naming-server:
    image: prathi233/mmv2-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    mem_reservation: 700m
    networks:
      - currency-network

  # docker run -p 9411:9411 openzipkin/zipkin:latest
  zipkin-server:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    mem_reservation: 300m
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    networks:
      - currency-network
  #    restart: always

  # docker run -p 5672:5672 rabbitmq:3.8.23-management
  rabbitmq:
    image: rabbitmq:3.8.23-management
    ports:
      - "5672:5672"   # communication port
      - "15672:15672" # management port
    mem_reservation: 300m
    networks:
      - currency-network

networks:
  currency-network:
